kind: ConfigMap
apiVersion: v1
metadata:
  name: application-properties
data:
  application-properties.yaml: | 
    management:
      endpoint:
        health:
          show-details: always
      endpoints:
        web:
          exposure:
            include: ["health", "info", "env","bus-refresh", "refresh"]

    spring:
      application:
        name: amq-test
      activemq:
        broker-url: tcp://amq-hdls-svc:5672
        user: admin
        password: admin
      jms:
        pub-sub-domain: true

    server:
      servlet:
        context-path: /amq/api
        port: 8080