apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
bases:
#- ../../base
- ../db
patchesStrategicMerge:
- metadata-db-deployment.yaml
resources:
- metadata-db-serviceaccount.yaml
