---

ansible_user: openshift
ansible_become: True

deployment_type: openshift-enterprise
openshift_deployment_type: openshift-enterprise
openshift_master_cluster_method: native
openshift_master_cluster_hostname: "{{ groups.lb.0 }}"
openshift_master_cluster_public_hostname: "{{ groups.lb.0 }}"
openshift_master_default_subdomain: "apps.{{ env_id }}.{{ public_dns_domain }}"

#openshift_deployment_type: openshift-enterprise
openshift_release: v3.7
#openshift_master_default_subdomain: "apps.{{ env_id }}.{{ public_dns_domain }}"

# HTPASSWD Identity Provider
openshift_master_identity_providers:
 - 'name': 'htpasswd_auth'
   'login': 'true'
   'challenge': 'true'
   'kind': 'HTPasswdPasswordIdentityProvider'
   'filename': '/etc/origin/master/htpasswd'
   
openshift_master_htpasswd_users:
  admin: $apr1$7aiANAYb$TOUYVUqnBqBlD5AQEIMYw1   

openshift_logging_install_logging: true
openshift_logging_es_pvc_size: 100Gi
openshift_logging_es_cluster_size: 3
openshift_logging_es_number_of_replicas: 2
openshift_logging_kibana_replica_count: 1
openshift_logging_es_nodeselector: 
  region: infra
openshift_logging_kibana_nodeselector: 
  region: infra
openshift_logging_curator_nodeselector: 
  region: infra

openshift_metrics_install_metrics: true
#openshift_hosted_metrics_storage_kind: dynamic
openshift_metrics_hawkular_nodeselector:
  region: infra
openshift_metrics_cassandra_nodeselector: 
  region: infra
openshift_metrics_heapster_nodeselector: 
  region: infra  
openshift_metrics_selector: "region=infra" 
openshift_metrics_cassandra_pvc_size: 10Gi
openshift_metrics_hawkular_replicas: 2
openshift_metrics_cassandra_replicas: 3
openshift_metrics_install_hawkular_agent: true 

openshift_node_labels: "{{ openstack.metadata.node_labels}}"

osm_default_node_selector: 'region=primary'
osm_use_cockpit: true
osm_cockpit_plugins: 
- 'cockpit-kubernetes'

openshift_docker_options: "--log-driver=json-file --log-opt max-size=50m --log-opt max-file=100"

openshift_cloudprovider_kind: openstack
openshift_cloudprovider_openstack_auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
openshift_cloudprovider_openstack_username: "sa_casl_contrib"
openshift_cloudprovider_openstack_password: "UKyq9t752A73CfqD"
openshift_cloudprovider_openstack_domain_name: Default
openshift_cloudprovider_openstack_tenant_id: "{{ lookup('env','OS_PROJECT_ID') }}"
openshift_cloudprovider_openstack_tenant_name: "{{ lookup('env','OS_PROJECT_NAME') }}"
openshift_cloudprovider_openstack_region: "{{ lookup('env','OS_REGION_NAME') }}"
openshift_cloudprovider_openstack_lb_subnet_id: 89dc38ac-8e32-43ca-8861-da0509969769

os_sdn_network_plugin_name: 'redhat/openshift-ovs-networkpolicy'
#os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'

openshift_disable_check: 
  - docker_storage
  - memory_availability
  - disk_availability
  
openshift_enable_service_catalog: true
openshift_template_service_broker_namespaces: 
  - openshift
openshift_hosted_etcd_storage_kind: dynamic     
  
#cloudforms settings
openshift_cfme_install_app: true
openshift_management_install_beta: true
openshift_management_app_template: cfme-template
openshift_management_storage_class: cloudprovider 

targetd_lvm_physical_volumes: /dev/vdb
targetd_iscsi_target: iqn.2003-01.org.example.mach1:1234
iscsi_provisioner_pullspec: quay.io/external_storage/iscsi-controller:latest
iscsi_provisioner_portals: 192.168.99.16:3260
chap_auth_discovery: true
discovery_sendtargets_auth_username: discovery_initiator_username
discovery_sendtargets_auth_password: discovery_initiator_password
discovery_sendtargets_auth_username_in: discovery_target_username
discovery_sendtargets_auth_password_in: discovery_target_password
chap_auth_session: true
session_auth_username: session_initiator_username
session_auth_password: session_initiator_password
session_auth_username_in: session_target_username
session_auth_password_in: session_target_password

#gluster
openshift_storage_glusterfs_namespace: glusterfs 
openshift_storage_glusterfs_name: storage
openshift_storage_glusterfs_nodeselector: "region=infra"
openshift_storage_glusterfs_storageclass: true
openshift_storage_glusterfs_block_deploy: true
openshift_storage_glusterfs_block_host_vol_create: true
openshift_storage_glusterfs_s3_deploy: true
openshift_storage_glusterfs_heketi_admin_key: admin
openshift_storage_glusterfs_heketi_user_key: user

#crio
#openshift_use_crio: true
#openshift_crio_enable_docker_gc: true

#audit
openshift_master_audit_config: 
  enabled: true 
  auditFilePath: /var/log/ocp-audit.log
  maximumFileRetentionDays: 2
  maximumFileSizeMegabytes: 50
  maximumRetainedFiles: 5

#alpha features
osm_api_server_args:
  feature-gates: 
  - PersistentLocalVolumes=true
  - AdvancedAuditing=true
osm_controller_args:
  feature-gates:
  - PersistentLocalVolumes=true
  
#prometheus
openshift_hosted_prometheus_deploy: true
#openshift_prometheus_storage_kind=glusterfs
openshift_prometheus_namespace: openshift-metrics
openshift_prometheus_node_selector: 
  region: infra
openshift_prometheus_storage_type: pvc
openshift_prometheus_alertmanager_storage_type: pvc
openshift_prometheus_alterbuffer_storage_type: pvc
openshift_prometheus_pvc_name: prometheus-data
openshift_prometheus_alertmanager_pvc_name: alertmanager-data
openshift_prometheus_alterbuffer_pvc_name: alertbuffer-data
openshift_prometheus_pvc_size: 3G
openshift_prometheus_alertmanager_pvc_size: 1G
openshift_prometheus_alertbuffer_pvc_size: 2G
openshift_prometheus_pvc_access_modes: [ReadWriteOnce]






