apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./kustomize/openshift-scc
  - ./kustomize/istio
  - ./kustomize/argo/overlays/istio
  - ./kustomize/centraldashboard/overlays/istio