apiVersion: v1
kind: Template
labels:
  template: coherence
metadata:
  annotations:
    description: Coherence cluster
  name: coherence
objects:
- apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    labels:
      application: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    replicas: "${{INSTANCES}}"
    selector:
      matchLabels:
        application: "${APPLICATION_NAME}"
    serviceName: "${APPLICATION_NAME}"
    template:
      metadata:
        labels:
          application: "${APPLICATION_NAME}"
      spec:
        containers:
        - env:
          - name: JAVA_OPTS
            value: "${JAVA_OPTS}"
          - name: COH_EXTEND_PORT
            value: "${COH_EXTEND_PORT}"
          - name: COH_WKA
            value: "${APPLICATION_NAME}.${NAMESPACE}.svc"                            
          image: "docker-registry.default.svc:5000/coherence/coherence:12.2.1.2.0-standalone"
          imagePullPolicy: Always
          name: "${APPLICATION_NAME}"
          ports:
          - containerPort: 8088
            protocol: TCP  
          - containerPort: "${{COH_EXTEND_PORT}}"
            protocol: TCP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      application: "${APPLICATION_NAME}"
    name: "${APPLICATION_NAME}"
  spec:
    clusterIP: None
    ports:
    - name: 8088-tcp
      port: 8088
      containerPort: 8088
      protocol: TCP  
    - name: "${COH_EXTEND_PORT}-tcp"
      port: "${{COH_EXTEND_PORT}}"
      containerPort: "${{COH_EXTEND_PORT}}"
      protocol: TCP
    selector:
      application: "${APPLICATION_NAME}"                             
parameters:
- description: The name for the application.
  name: APPLICATION_NAME
  required: false
  value: coherence
- description: The java opts.
  name: JAVA_OPTS
  required: false
  value: "-Xmx1G -Xms1G"
- description: The extend port.
  name: COH_EXTEND_PORT
  required: false
  value: "20000"    
- description: The number of instances.
  name: INSTANCES
  required: false
  value: "1"    
- description: The namespace in which this service will be running.
  name: NAMESPACE
  required: true  